name: Hugging Face Inference Endpoint integration tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_target_matrix:
    outputs:
      repositories: ${{ steps.extract.outputs.repositories }}

    runs-on: ubuntu-latest
    env:
      HFENDPOINTS_MODEL_REPOSITORIES: "whisper-vllm-gpu;embeddings-llamacpp-cpu"

    steps:
      # Extract the comma separated list of repository to individual HFENDPOINTS_MODEl_REPOSITORY_<index>=<model_id>
      - name: "Extract image repositories"
        id: "extract"
        run: |
          IFS=';' read -r -a __repositories__ <<< "${HFENDPOINTS_MODEL_REPOSITORIES}"
          REPOSITORIES_JSON_ARRAY=$(jq -c -n '$ARGS.positional' --args "${__repositories__[@]}")
          REPOSITORIES_JSON_OBJECT=$(jq -c -n --argjson repositories ${REPOSITORIES_JSON_ARRAY} -f <(echo '{"repository":$repositories}'))

          echo "Executing integration tests on the following repositories: ${REPOSITORIES_JSON_ARRAY}" >> $GITHUB_STEP_SUMMARY
          echo "repositories=${REPOSITORIES_JSON_OBJECT}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build_target_matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.build_target_matrix.outputs.repositories) }}
      max-parallel: 10
    steps:
      - name: "Install hfjobs"
        run: python3 -m pip install hfjobs huggingface_hub

      #      TODO: Check with Hugo
      #      - uses: actions/checkout@v4
      #        with:
      #          repository: huggingface/hf-cli
      #          fetch-depth: '1'
      #          ref: 'main'
      #          token: ${{ secrets.HUGGINGFACE_CLI_TOKEN }}
      #
      #      - uses: actions-rust-lang/setup-rust-toolchain@v1
      #      - name: "Build & install Hugging Face CLI"
      #        run: cargo build --release hf-cli

      - name: "Fetch endpoint specs"
        run: |
          echo "Fetching repository .hfjobs content for ${{ matrix.repository }}"
          huggingface-cli login ${{ secrets.HUB_HFENDPOINTS_IMAGES_ORG_TOKEN }}
          huggingface-cli download hfendpoints-images/${{ matrix.repository }} --cache-dir /tmp/${{ matrix.repository }}



