name: Hugging Face Inference Endpoint integration tests
on:
  pull_request:
    branches:
      - main

jobs:
  build_target_matrix:
    outputs:
      REPOSITORIES: string

    runs-on: ubuntu-latest
    env:
      HFENDPOINTS_MODEL_REPOSITORIES: "whisper-vllm-gpu;embeddings-llamacpp-cpu"

    steps:
      # Extract the comma separated list of repository to individual HFENDPOINTS_MODEl_REPOSITORY_<index>=<model_id>
      - name: "Extract image repositories"
        run: |
          IFS=';' read -r -a __repositories__ <<< "${HFENDPOINTS_MODEL_REPOSITORIES}"
          REPOSITORIES_JSON_ARRAY=`(jq -c -n '$ARGS.positional' --args "${__repositories__[@]}")`
          REPOSITORIES_JSON_OBJECT=`(jq -n --argjson __repositories__ $REPOSITORIES_JSON_ARRAY -f <(echo \'{"repository":$__repositories__}\'))`

          echo "Executing integration tests on the following repositories: ${REPOSITORIES_JSON_ARRAY}" >> $GITHUB_STEP_SUMMARY
          echo "REPOSITORIES=${REPOSITORIES_JSON_OBJECT}" >> "$GITHUB_OUTPUT"

  deploy_endpoints:
    runs-on: ubuntu-latest
    needs: build_target_matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.build_target_matrix.outputs.REPOSITORIES) }}
    steps:
      - name: "Fetch endpoint specs"
        run: echo ${{ matrix.repository }}
