name: Hugging Face Inference Endpoint integration tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_target_matrix:
    outputs:
      repositories: ${{ steps.extract.outputs.repositories }}

    runs-on: ubuntu-latest
    env:
      HFENDPOINTS_MODEL_REPOSITORIES: "whisper-vllm-gpu;embeddings-llamacpp-cpu"

    steps:
      # Extract the comma separated list of repository to individual HFENDPOINTS_MODEl_REPOSITORY_<index>=<model_id>
      - name: "Extract image repositories"
        id: "extract"
        run: |
          IFS=';' read -r -a __repositories__ <<< "${HFENDPOINTS_MODEL_REPOSITORIES}"
          REPOSITORIES_JSON_ARRAY=$(jq -c -n '$ARGS.positional' --args "${__repositories__[@]}")
          REPOSITORIES_JSON_OBJECT=$(jq -c -n --argjson repositories ${REPOSITORIES_JSON_ARRAY} -f <(echo '{"repository":$repositories}'))

          echo "Executing integration tests on the following repositories: ${REPOSITORIES_JSON_OBJECT}" >> $GITHUB_STEP_SUMMARY
          echo "repositories=${REPOSITORIES_JSON_ARRAY}" >> "$GITHUB_OUTPUT"

  deploy_endpoints:
    runs-on: ubuntu-latest
    needs: build_target_matrix
    steps:
      - run: "echo ${{ needs.build_target_matrix.outputs.repositories }}"
#    strategy:
#      fail-fast: true
#      matrix: ${{ fromJson(needs.build_target_matrix.outputs.repositories) }}
#    steps:
#      - name: "Fetch endpoint specs"
#        run: echo ${{ matrix.repository }}
