name: Hugging Face Inference Endpoint integration tests
on:
  pull_request:
    branches:
      - main

jobs:
  build_target_matrix:
    runs-on: ubuntu-latest
    env:
      HFENDPOINTS_MODEL_REPOSITORIES: "hfendpoints-images/whisper-vllm-gpu;"

    steps:
      - name: "Extract image repositories"
        run: |
          IFS=';' read -r -a repositories <<< "${HFENDPOINTS_MODEL_REPOSITORIES}"
          echo "Fetching deployment information for: $repositories"
          for index in "${!repositories[@]}"; do echo "HFENDPOINTS_MODEL_REPOSITORIES_${index}=${repositories[$index]}" >> "$GITHUB_ENV"; done
          echo "HFENDPOINTS_MODEL_REPOSITORIES_COUNT=${#repositories[@]}" >> "$GITHUB_ENV"

      - name: "Build matrix"
        run: |
          for index in $(seq 1 $HFENDPOINTS_MODEL_REPOSITORIES_COUNT); do
            REPOSITORY=HFENDPOINTS_MODEL_REPOSITORIES_$index
            echo "Repository #${index}: ${!REPOSITORY}"
          done