name: Hugging Face Inference Endpoint integration tests
on:
  pull_request:
    branches:
      - main

jobs:
  build_target_matrix:
    runs-on: ubuntu-latest
    env:
      HFENDPOINTS_MODEL_REPOSITORIES: "whisper-vllm-gpu;embeddings-llamacpp-cpu"

    steps:
      # Extract the comma separated list of repository to individual HFENDPOINTS_MODEl_REPOSITORY_<index>=<model_id>
      - name: "Extract image repositories"
        run: |
          IFS=';' read -r -a repositories <<< "${HFENDPOINTS_MODEL_REPOSITORIES}"
          REPOSITORY_JSON=`jq -c -n '$ARGS.positional' --args "${repositories[@]}"`
          echo "repository=`jq -n --argjson repository $REPOSITORY_JSON -f <(echo '{"repository":[$repository]}')`" >> "$GITHUB_OUTPUT"

  deploy_endpoints:
    runs-on: ubuntu-latest
    needs: build_target_matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.build_target_matrix.outputs.repositories) }}
    steps:
      - name: "Fetch endpoint specs"
        run: echo ${{ matrix.repository }}
