name: Rust

on:
  push:
    branches: [ "main", "hfendpoints-v*.*", "whisper-rust" ]
  pull_request:
    branches: [ "main", "hfendpoints-v*.*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Basic actions that must pass before we kick off more expensive tests.
  basics:
    name: QA Checks
    runs-on: ubuntu-latest
    needs:
      - clippy
      - fmt
    steps:
      - run: exit 0

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2

      # Check fmt
      - name: "rustfmt --check"
        run: rustfmt --check --edition 2024

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      # Run clippy
      - name: "clippy --all"
        run: cargo clippy --all --tests --all-features --no-deps

  #  docs:
  #    name: docs
  #    runs-on: ${{ matrix.run.os }}
  #    strategy:
  #      matrix:
  #        run:
  #          - os: windows-latest
  #          - os: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Install Rust ${{ env.rust_nightly }}
  #        uses: dtolnay/rust-toolchain@stable
  #        with:
  #          toolchain: ${{ env.rust_nightly }}
  #      - uses: Swatinem/rust-cache@v2
  #      - name: "doc --lib --all-features"
  #        run: |
  #          cargo doc --lib --no-deps --all-features --document-private-items
  #        env:
  #          RUSTFLAGS: --cfg docsrs
  #          RUSTDOCFLAGS: --cfg docsrs  -Dwarnings

#  hfendpoints-workspace:
#    needs: basics
#    name: Build & tests hfendpoints
#    strategy:
#      matrix:
#        os: [ windows-latest, ubuntu-latest, macos-latest ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build
#        run: cargo build --verbose
#      - name: Run tests
#        run: cargo test --verbose

  hfendpoints-workspace-python:
    needs: basics
    name: Build & tests hfendpoints
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        python: [ 3.12, 3.13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --features python --verbose
      - name: Run tests
        run: cargo test --features python --verbose